apiVersion: karpenter.k8s.aws/v1beta1
kind: EC2NodeClass
metadata:
  name: default
spec:
  amiFamily: AL2
  role: ${ec2_role_name}
  subnetSelectorTerms:
  - tags:
      karpenter.sh/discovery: ${cluster_name}
  securityGroupSelectorTerms:
  - tags:
      karpenter.sh/discovery: ${cluster_name}
  tags:
    karpenter.sh/discovery: ${cluster_name}
